---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "FCOS Rolling"

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container:
      image: quay.io/coreos/butane:release
      options: --privileged
    steps:
      - name: Install Workflow Tools
        shell: bash
        run: |
          dnf install -y git

      - name: Checkout
        uses: actions/checkout@v4
